version: '3.8'

services:
  web:
    build: .
    image: 831192075102.dkr.ecr.ap-northeast-2.amazonaws.com/wasso/prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - wasso_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  static_volume:
  media_volume:

networks:
  wasso_network:
    name: wasso_network