# Generated by Django 5.1.4 on 2025-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_pcsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcsession',
            name='is_used',
        ),
        migrations.AddField(
            model_name='pcsession',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('authenticated', 'Authenticated'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
