# Generated by Django 5.1.4 on 2025-07-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_absentapply_approved_by'),
        ('userapp', '0003_remove_pcsession_is_used_pcsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcsession',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
