# Generated by Django 5.1.4 on 2025-08-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_pcsession_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
