# Generated by Django 5.1.4 on 2025-08-18 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_fcmtoken_uniquetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquetoken',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquetoken',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquetoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'Ios'), ('unknown', 'Unknown')], default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uniquetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
