# Generated by Django 5.1.3 on 2024-11-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendances',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('attendance_start_datetime', models.DateTimeField()),
                ('attendance_end_datetime', models.DateTimeField()),
                ('late_tolerance_minutes', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('qr_code_url', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
