# Generated by Django 5.1.4 on 2024-12-25 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="title",
        ),
    ]
