# Generated by Django 5.1.4 on 2025-01-19 16:07

import django.contrib.postgres.fields
import storages.backends.s3
from django.db import migrations, models

import event.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(
                    storage=storages.backends.s3.S3Storage(),
                    upload_to=event.models.event.event_image_path,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
