# Generated by Django 5.1.4 on 2025-01-26 11:08

import storages.backends.s3
from django.db import migrations, models

import event.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="qr_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="qr_code_url",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=event.models.event.event_qr_code_path,
            ),
        ),
    ]
