# Generated by Django 5.1.4 on 2025-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_attendance_latitude_attendance_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
