# Generated by Django 5.1.4 on 2025-01-19 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="absence_minutes",
            new_name="fail_minutes",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="late_tolerance_minutes",
            new_name="late_minutes",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="begin_minutes",
            new_name="start_minutes",
        ),
        migrations.RemoveField(
            model_name="event",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="longitude",
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_datetime",
            field=models.TimeField(),
        ),
    ]
