# Generated by Django 5.1.4 on 2025-01-19 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_rename_absence_minutes_event_fail_minutes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_datetime",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_datetime",
            new_name="start_time",
        ),
    ]
