# Generated by Django 5.1.4 on 2025-01-19 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
