# Generated by Django 5.1.4 on 2025-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[("kakao", "Kakao"), ("google", "Google"), ("apple", "Apple")],
                default="kakao",
                max_length=255,
            ),
        ),
    ]
