# Generated by Django 5.1.4 on 2025-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_user_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
