# Generated by Django 5.1.4 on 2025-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="push_allow",
            field=models.BooleanField(default=True),
        ),
    ]
