# Generated by Django 5.1.4 on 2025-02-15 13:18

import api.event.models.event
import django.contrib.postgres.fields
import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'absent_applies',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '출석'), (2, '지각'), (3, '결석')], default=1)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_modified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendances',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_minutes', models.IntegerField()),
                ('late_minutes', models.IntegerField()),
                ('fail_minutes', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code_url', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=api.event.models.event.event_qr_code_path)),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=api.event.models.event.event_image_path), blank=True, default=list, null=True, size=None)),
                ('attendance_type', models.CharField(choices=[('QR', 'QR'), ('LOCATION', 'Location'), ('BOTH', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
