# Generated by Django 5.1.4 on 2025-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_deleted_club_deleted_at_generation_deleted_and_more'),
        ('event', '0005_attendance_created_at_attendance_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentapply',
            name='user',
        ),
        migrations.AddField(
            model_name='absentapply',
            name='gen_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.genmember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absentapply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absentapply',
            name='status',
            field=models.IntegerField(choices=[(0, '인증전'), (1, '출석'), (2, '지각'), (3, '결석')], default=1),
        ),
    ]
