# Generated by Django 5.1.4 on 2025-04-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_deleted_club_deleted_at_generation_deleted_and_more'),
        ('event', '0006_remove_absentapply_user_absentapply_gen_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentapply',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_absent_applies', to='club.genmember'),
        ),
    ]
