# Generated by Django 5.1.4 on 2025-08-06 09:22

import api.event.models.edit_request
import django.contrib.postgres.fields
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_member_short_description'),
        ('event', '0007_absentapply_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=api.event.models.edit_request.event_image_path), blank=True, default=list, null=True, size=None)),
                ('status', models.IntegerField(choices=[(0, '인증전'), (1, '출석'), (2, '지각'), (3, '결석')], default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edit_requests', to='club.genmember')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('gen_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.genmember')),
            ],
        ),
    ]
