# Generated by Django 5.1.4 on 2025-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
