# Generated by Django 5.1.4 on 2025-08-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_event_end_time_remove_event_start_time_and_more'),
        ('userapp', '0007_uniquetoken_last_login_uniquetoken_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unique_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='userapp.uniquetoken'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='event.event'),
        ),
        migrations.CreateModel(
            name='Abusing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.attendance')),
            ],
            options={
                'db_table': 'abusing',
            },
        ),
    ]
