# Generated by Django 5.1.4 on 2025-08-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_attendance_unique_token_alter_attendance_event_and_more'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentapply',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_absent_applies', to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='absentapply',
            name='gen_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='generation_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edit_requests', to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='gen_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.genmember'),
        ),
        migrations.AlterField(
            model_name='event',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.generation'),
        ),
    ]
