# Generated by Django 5.1.4 on 2025-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_attendance_unique_token_alter_attendance_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentapply',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
