# Generated by Django 5.1.4 on 2025-01-19 14:34

from django.db import migrations, models

import club.models.club


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="image_url",
        ),
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=club.models.club.club_image_path
            ),
        ),
    ]
