# Generated by Django 5.1.3 on 2024-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclub',
            name='generation',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userclub',
            name='join_date',
            field=models.DateTimeField(),
        ),
    ]
