# Generated by Django 5.1.4 on 2025-01-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="last_user_generation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_member",
                to="club.generationmapping",
            ),
        ),
    ]
