# Generated by Django 5.1.4 on 2025-01-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubapply",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clubapply",
            name="generation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="club.generation"
            ),
        ),
    ]
