# Generated by Django 5.1.4 on 2025-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="last_user_generation",
        ),
        migrations.AddField(
            model_name="generationmapping",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
