# Generated by Django 5.1.4 on 2025-01-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_clubapply_accepted_at_alter_clubapply_generation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclub",
            name="last_generation",
        ),
        migrations.AddField(
            model_name="userclub",
            name="last_user_generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club.usergeneration",
            ),
        ),
    ]
