# Generated by Django 5.1.4 on 2025-01-19 16:07

import storages.backends.s3
from django.db import migrations, models

import club.models.club


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_remove_club_image_url_club_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=club.models.club.club_image_path,
            ),
        ),
    ]
