# Generated by Django 5.1.4 on 2025-01-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_club_current_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_club",
                to="club.role",
            ),
        ),
    ]
