# Generated by Django 5.1.4 on 2025-01-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0004_remove_userclub_last_generation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclub",
            name="last_user_generation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="club.usergeneration"
            ),
        ),
    ]
