# Generated by Django 5.1.4 on 2025-02-15 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
        migrations.AddField(
            model_name='clubapply',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.generation'),
        ),
        migrations.AddField(
            model_name='club',
            name='current_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_club', to='club.generation'),
        ),
        migrations.AddField(
            model_name='generationmapping',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.generation'),
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.club'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationmapping',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member'),
        ),
        migrations.AddField(
            model_name='role',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
        migrations.AddField(
            model_name='generationmapping',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.role'),
        ),
        migrations.AddField(
            model_name='club',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_club', to='club.role'),
        ),
    ]
