# Generated by Django 5.1.4 on 2025-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
        ('event', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerationMapping',
            new_name='GenMember',
        ),
        migrations.AddField(
            model_name='club',
            name='notion_database_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
