# Generated by Django 5.1.4 on 2025-02-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_rename_generationmapping_genmember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='done',
            new_name='activated',
        ),
        migrations.RemoveField(
            model_name='club',
            name='notion_page_id',
        ),
    ]
