# Generated by Django 5.1.4 on 2025-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_deleted_club_deleted_at_generation_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
