# Generated by Django 5.1.4 on 2025-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_generation_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
