# Generated by Django 5.1.4 on 2025-08-07 07:36

import api.club.models.member
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_member_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=api.club.models.member.member_profile_image_path),
        ),
    ]
