# Generated by Django 5.1.4 on 2025-08-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
