# Generated by Django 5.1.4 on 2025-08-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_club_short_description_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_members', to='club.generation'),
        ),
        migrations.AlterField(
            model_name='genmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_members', to='club.member'),
        ),
    ]
