# Generated by Django 5.1.4 on 2025-08-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_genmember_generation_alter_genmember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
