# Generated by Django 5.1.4 on 2025-08-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_member_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubapply',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='clubapply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='club',
        ),
        migrations.RemoveField(
            model_name='genmember',
            name='generation',
        ),
    ]
