# Generated by Django 5.1.4 on 2025-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_member_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='history_edit',
            field=models.BooleanField(default=False),
        ),
    ]
