# Generated by Django 5.1.4 on 2025-08-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_role_history_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='deleted_at',
        ),
    ]
