# Generated by Django 5.1.4 on 2025-08-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_remove_clubapply_generation_remove_clubapply_user_and_more'),
        ('event', '0013_alter_absentapply_approved_by_and_more'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='current_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_club', to='generation.generation'),
        ),
        migrations.RemoveField(
            model_name='genmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='genmember',
            name='role',
        ),
        migrations.DeleteModel(
            name='ClubApply',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
        migrations.DeleteModel(
            name='GenMember',
        ),
    ]
