# Generated by Django 5.1.4 on 2025-08-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_rename_deleted_generation_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapply',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_applies', to='club.generation'),
        ),
    ]
